interface UserInfo {
  activitiSync: number
  avatar: string
  birthday: string
  bpmStatus: string
  clientId: string
  createBy: string
  createTime: string
  delFlag: number
  departIds: string
  email: string
  homePath: string
  id: string
  izBindThird: false
  loginTenantId: number
  orgCode: string
  orgCodeTxt: string
  phone: string
  post: string
  postText: string
  realname: string
  relTenantIds: string
  sex: number
  sign: string
  signEnable: string
  status: number
  telephone: string
  updateBy: string
  updateTime: string
  userIdentity: number
  username: string
  workNo: string
}
