<script lang="ts" setup>
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { Snackbar } from '@varlet/ui'
import NavBar from '@/views/components/NavBar.vue'
const route = useRoute()
const title = ref<string>('原生能力')
onMounted(() => {
  console.log('Plus Api ---> ', route.query)
  title.value = route.query.title as string
  if (!window.plus) {
    Snackbar.warning('非Andndroid平台，加载失败！')
  }
})
</script>
<template>
  <div>
    <NavBar :title="title" />
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
    <div>安卓原生</div>
  </div>
</template>
